### ISSUE TITLE
Add an about page and the link at the homepage

### ISSUE THREAD

**Issue by AntonioDaria** [Kharouk/CameronCam#26]
Add the actual page when you scroll all the way down

- [x] Add the Link to the Header Component
- [x] When you click on the link, it goes to the bottom of the website in the about section (scroll or direct?)
- [x] Add identifier that shows what page you are on.

**Comment by Kharouk** [comment]
- [x] Add the Link to the Header Component
- [ ] When you click on the link, it goes to the bottom of the website in the about section (scroll or direct?)
- [ ] Add identifier that shows what page you are on.
